# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180410_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, help_text='1400*300', null=True, upload_to='post/', verbose_name='\u914d\u56fe'),
        ),
    ]
