# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-19 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u5b66\u9662')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u9662\u957f')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u8bfe\u7a0b\u7c7b\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u8bfe\u7a0b\u540d')),
                ('code', models.CharField(max_length=32, verbose_name='\u8bfe\u7a0b\u4ee3\u7801')),
                ('numbering', models.CharField(max_length=32, verbose_name='\u8bfe\u7a0b\u5e8f\u53f7')),
                ('total_points', models.IntegerField(default=100, verbose_name='\u603b\u5206')),
                ('credit', models.FloatField(verbose_name='\u5b66\u5206')),
                ('midterm', models.FloatField(default=0, help_text='\u6309\u5c0f\u6570\u586b\u5199\uff0c\u5982 0.1', verbose_name='\u671f\u4e2d\u8003\u8bd5\u6bd4\u4f8b')),
                ('final_exam', models.FloatField(default=1, help_text='\u6309\u5c0f\u6570\u586b\u5199\uff0c\u5982 0.1', verbose_name='\u671f\u672b\u8003\u8bd5\u6bd4\u4f8b')),
                ('usual', models.FloatField(default=0, help_text='\u6309\u5c0f\u6570\u586b\u5199\uff0c\u5982 0.1', verbose_name='\u5e73\u65f6\u6210\u7ee9\u6bd4\u4f8b')),
                ('experimental', models.FloatField(default=0, help_text='\u6309\u5c0f\u6570\u586b\u5199\uff0c\u59820.1', verbose_name='\u5b9e\u9a8c\u6210\u7ee9\u6bd4\u4f8b')),
                ('admin', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u4efb\u8bfe\u6559\u5e08')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Category', verbose_name='\u8bfe\u7a0b\u7c7b\u522b')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u7cfb')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Academy', verbose_name='\u5b66\u9662')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7cfb\u4e3b\u4efb')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u73ed\u7ea7')),
                ('gradeId', models.CharField(max_length=32, verbose_name='\u73ed\u53f7')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7cfb')),
            ],
        ),
    ]
