# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Department', verbose_name='\u7cfb'),
        ),
    ]
