# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180320_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.IntegerField(choices=[(1, '1'), (2, '1')], default=1, verbose_name='\u5b66\u671f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(default=-1, help_text='\u59822017-2018', max_length=32, verbose_name='\u5b66\u5e74'),
            preserve_default=False,
        ),
    ]
