# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180320_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.TextField(default='', verbose_name='\u5907\u6ce8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='length',
            field=models.IntegerField(default=4, verbose_name='\u5b66\u5236'),
        ),
        migrations.AddField(
            model_name='department',
            name='train_direction',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u57f9\u517b\u65b9\u5411'),
        ),
    ]
