# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180320_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=32, unique=True, verbose_name='\u5b66\u5e74')),
                ('term', models.CharField(max_length=4, verbose_name='\u5b66\u671f')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='school_term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.SchoolTerm', verbose_name='\u5b66\u5e74\u5b66\u671f'),
            preserve_default=False,
        ),
    ]
