# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180321_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolterm',
            name='year',
            field=models.CharField(max_length=32, verbose_name='\u5b66\u5e74'),
        ),
    ]
