# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20180321_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='total_points',
            new_name='total_score',
        ),
    ]
