# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-03 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('\u5468\u4e00', '\u5468\u4e00'), ('\u5468\u4e8c', '\u5468\u4e8c'), ('\u5468\u4e09', '\u5468\u4e09'), ('\u5468\u56db', '\u5468\u56db'), ('\u5468\u4e94', '\u5468\u4e94'), ('\u5468\u516d', '\u5468\u516d'), ('\u5468\u65e5', '\u5468\u65e5')], max_length=2)),
                ('lesson', models.CharField(choices=[('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6'), ('7-8', '7-8'), ('\u665a\u81ea\u4e60', '\u665a\u81ea\u4e60')], max_length=3)),
            ],
        ),
    ]
