# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-03 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.ManyToManyField(blank=True, null=True, to='course.Schedule', verbose_name='\u6392\u8bfe'),
        ),
    ]
