# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20180403_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lesson',
            field=models.CharField(choices=[('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6'), ('7-8', '7-8'), ('night', 'night')], max_length=3),
        ),
    ]
