# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 06:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u5b66\u9662')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u8bfe\u7a0b\u540d')),
                ('total_points', models.IntegerField(default=100, verbose_name='\u603b\u5206')),
                ('rate', models.IntegerField(default=100, verbose_name='\u8003\u8bd5\u6210\u7ee9\u5360\u6bd4')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u7cfb')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.Academy', verbose_name='\u5b66\u9662')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u73ed\u7ea7')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.Department', verbose_name='\u7cfb')),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_points', models.FloatField(verbose_name='\u8003\u8bd5\u6210\u7ee9')),
                ('extre_points', models.FloatField(verbose_name='\u5e73\u65f6\u5206')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.AddField(
            model_name='user',
            name='intake',
            field=models.DateField(default=datetime.datetime(2018, 3, 13, 14, 5, 23, 359072), verbose_name='\u5165\u5b66\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7cfb\u4e3b\u4efb'),
        ),
        migrations.AddField(
            model_name='course',
            name='admin',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u4efb\u8bfe\u6559\u5e08'),
        ),
        migrations.AddField(
            model_name='academy',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u9662\u957f'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccount.Grade', verbose_name='\u73ed\u7ea7'),
        ),
    ]
