# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_auto_20180313_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='\u59d3\u540d'),
        ),
    ]
