# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='gradeId',
            field=models.CharField(default=123, max_length=32, verbose_name='\u73ed\u53f7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u73ed\u7ea7'),
        ),
    ]
