# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-19 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('useraccount', '0004_auto_20180317_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='course',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='department',
            name='academy',
        ),
        migrations.RemoveField(
            model_name='department',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='extre_points',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='test_points',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Grade', verbose_name='\u73ed\u7ea7'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='experimental',
            field=models.FloatField(blank=True, null=True, verbose_name='\u5b9e\u9a8c\u6210\u7ee9'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='final_exam',
            field=models.FloatField(blank=True, null=True, verbose_name='\u671f\u672b\u6210\u7ee9'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='midterm',
            field=models.FloatField(blank=True, null=True, verbose_name='\u671f\u4e2d\u6210\u7ee9'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='retest',
            field=models.FloatField(blank=True, null=True, verbose_name='\u8865\u8003\u6210\u7ee9'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='usual',
            field=models.FloatField(blank=True, null=True, verbose_name='\u5e73\u65f6\u6210\u7ee9'),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.DeleteModel(
            name='Academy',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
