# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_auto_20180319_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intake',
            field=models.DateField(blank=True, null=True, verbose_name='\u5165\u5b66\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stuId',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5b66\u53f7/\u6559\u804c\u5de5\u7f16\u53f7'),
        ),
    ]
