# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_auto_20180320_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='\u59d3\u540d'),
        ),
    ]
