# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_auto_20180320_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='at_school',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u5728\u6821'),
        ),
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.IntegerField(default=0, verbose_name='\u6240\u5c5e\u6821\u533a'),
        ),
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default='', verbose_name='\u5907\u6ce8'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.IntegerField(choices=[(0, '\u672c\u79d1'), (1, '\u7855\u58eb'), (2, '\u535a\u58eb')], default=0, verbose_name='\u5b66\u5386'),
        ),
        migrations.AddField(
            model_name='user',
            name='have_roll',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u5b66\u7c4d'),
        ),
        migrations.AddField(
            model_name='user',
            name='leave',
            field=models.DateField(blank=True, null=True, verbose_name='\u9884\u6bd5\u4e1a\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='user',
            name='method',
            field=models.IntegerField(choices=[(0, '\u666e\u901a\u5168\u65e5\u5236'), (1, '\u975e\u5168\u65e5\u5236')], default=0, verbose_name='\u5b66\u4e60\u5f62\u5f0f'),
        ),
        migrations.AddField(
            model_name='user',
            name='roll_in_school',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u5728\u7c4d'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6027\u522b'),
        ),
        migrations.AddField(
            model_name='user',
            name='term',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='\u6240\u5728\u5e74\u7ea7'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u59d3\u540d'),
        ),
    ]
