# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_auto_20180320_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='points',
            field=models.FloatField(blank=True, null=True, verbose_name='\u7ee9\u70b9'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='total_score',
            field=models.FloatField(blank=True, null=True, verbose_name='\u603b\u5206'),
        ),
    ]
