# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-09 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_auto_20180321_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=16, verbose_name='\u53cd\u9988\u7c7b\u578b')),
                ('message', models.CharField(max_length=256, verbose_name='\u53cd\u9988\u5185\u5bb9')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
